name: Auto-Generate Studies

permissions:
  contents: write        # ← allow the bot to push to this repo

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:                          # ← makes the secret visible to all steps
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Fetch new studies
        run: python scripts/fetch_studies.py

      - name: Commit data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/studies.json
          git diff --cached --quiet || git commit -m "Auto-update studies.json"
          git push
